server:
  port: 8080
spring:
  application:
    name: serverEureka
eureka:
  instance:
  hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
