server:
  port: 8092
  error:
    include-message: always

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka

# datasource
spring:
application:
    name: msFuncionario
    datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./ms-funcionario/data/bd-funcionario
    username: sa
    password:
  # jpa
    jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  # h2
    h2:
    console:
      enabled: true
      path: /h2-console
